# my global config
global:
  scrape_interval: 20s 
  evaluation_interval: 20s # Evaluate rules every 20 seconds.
# scrape_timeout is set to the global default (10s).
# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
- job_name: "patient_survival_app"
  metrics_path: '/metrics'
  scheme: 'https'
  scrape_interval: 10s # override default value
  scrape_timeout: 10s # override default value
  static_configs:
    - targets: ["refactored-space-potato-r7rvxvjg7wwhpv66-8001.app.github.dev"] 
